FROM node:22-alpine AS base

# Set the working directory
WORKDIR /src

# Install pnpm
RUN npm install -g pnpm

# Copy package.json and install dependencies
COPY package.json .
RUN pnpm install

# Copy the rest of your application code
COPY . .

# Start the application
CMD ["pnpm", "run", "dev"]
